### ISSUE TITLE
[feature-request] Community Edition

### ISSUE THREAD

**Issue by Minipada** [esimonetti/SugarDockerized#33]
Thanks for the repo, nice wok
It's not an issue by itself, but I'm trying to use your work for the community Edition. I'm used to Docker but not SugarCRM.
I downloaded the sourceforge version but can't make it work, some databases are not completely initialized and installation fails. Would you know where to continue from this?

**Comment by esimonetti** [comment]
Hi Minipada,
Thank you for the feedback.

This stack has been designed specifically to support Sugar commercial editions development.

If you do want to implement it yourself, you would have to add the platform components used by your selected SugarCRM community version (eg: PHP 5.3, MySQL 5.5, Elasticsearch 0.90.10)

I hope this helps you move forward.
Regards,
Enrico Simonetti
