### ISSUE TITLE
Sugar stack 80 xdebug settings

### ISSUE THREAD

**Issue by michaelwjoyner** [esimonetti/SugarDockerized#40]
On the 80 stack, the **xdebug.remote.enabled** is off. 
I needed to hack .htaccess to get by.
I also request that **xdebug.remote_connect_back** be set to true. For those of us let our Docker Box sit in the corner of the room and work from a remote workstation. :-)

**Comment by esimonetti** [comment]
Hi Michael,

I do provide the ability of building the stack locally as well, by leveraging, for version 8.0, the following docker compose file for example https://github.com/esimonetti/SugarDockerized/blob/master/stacks/sugar8/php71-local-build.yml.

If you do follow this process, you could just checkout the repository, modify the image's config files and use that yml file to build your images.

Also the htaccess is a pretty good solution for development.

I find it really useful if I have to test specific settings or adding software packages on the fly

Hope it helps!
