### ISSUE TITLE
Problem with fresh Sugar installation

### ISSUE THREAD

**Issue by pnlem** [esimonetti/SugarDockerized#42]
Hello, 
I cloned your repository and I tried to install a SugarCRM Ent 8.0.1 from scratch. I'm having an issue with the AllowOverride parameters during the installation. 
<img width="749" alt="capture d ecran 2018-11-05 a 13 51 51" src="https://user-images.githubusercontent.com/5112027/48002583-3fbce000-e10c-11e8-9d43-36e10a3cbdcb.png">

Do you know how I can fix the problem ? It's working with a existing instance. 

Regards,

Pierre-Nicolas

**Comment by esimonetti** [comment]
Hi Pierre-Nicolas,

It most likely has to do with the network/url rewriting configuration.
What url do you use to access the docker setup?
What host file entries do you have?
Do you use a VM or a local instance?
Does your VM have the right host file entries to match your request routing?

Once the url matches the host files entries and those entries are known by every party involved, it should all work fine.

Hope it helps

**Comment by pnlem** [comment]
Hi Enrico, 
Thank you for your answer. I'm using Docker on Mac without virtual machine. I changed the apache and mysql port because I already have one apache/mysql on ports 80 and 3306. So I'm accessing to apache by http://localhost:81/sugar and mysql on 3307. I added all sugar files to the sugar folder. 

In my host file I have the following : 
127.0.0.1       localhost
127.0.0.1       docker.local

One more question, I'm using your SugarDockerized tools since a while and before I was able to access to the sugar database with Sequel or MySQLWorkbench. I tried yesterday and it's not working after an update of the git project. Is it something related to my local hosts ? 

![capture d ecran 2018-11-06 a 10 15 57](https://user-images.githubusercontent.com/5112027/48054201-fbcde780-e1ac-11e8-8840-a21222340672.png)

Regards,

Pierre-Nicolas

**Comment by esimonetti** [comment]
How about http://docker.local:81/sugar ?
If that does not work, I would try to move the other services' to alternative ports

I do not see why it would not work to connect to the db. Can you do it via command line? Use 127.0.0.1 to connect. I found problems with localhost and docker on mysql for some reason.

**Comment by pnlem** [comment]
Ok thank you for your feedback. I tried with the docker.local:81 and it's the same problem. I will try with virtual box and start a new config again. Docker on Mac is very very slow... :) 
I will let you know. 

Pierre-Nicolas

**Comment by esimonetti** [comment]
As I have not heard from you in a while with an update, I assume it worked with the VirtualBox image.
I will proceed on closing the issue.
