### ISSUE TITLE
utilities/backup.sh throws error when trying mysqldump

### ISSUE THREAD

**Issue by torrios** [esimonetti/SugarDockerized#54]
When trying to backup an environment I get the following output:

> ./utilities/backup.sh: line 36: mysqldump: command not found
> Database NOT backed up!!! Please check that the "sugar" database exists!
> Please discard the current backup

If I'm not mistaken the script assumes that the command mysqldump exists on the host system which is not documented in the README. I'm using the Linux VM and this does not have **mysqldump** installed.

Would it make sense for the script to execute the **mysqldump** from inside the **sugar-mysql** container?

Thanks

**Comment by esimonetti** [comment]
Hector,
Thanks for bringing this to my attention.
I modified the script backup.sh and restore.sh to leverage the mysql container when acting against mysql.
I added a check to confirm if rsync is running on the local machine and output a message if not existent.

This has been just merged with PR 55 https://github.com/esimonetti/SugarDockerized/pull/55 together with some other fixes and with a travis-ci change in behaviour that would make all the automation fail.

Cheers
