### ISSUE TITLE
Sugar Unit Test

### ISSUE THREAD

**Issue by ShadMickelberry** [esimonetti/SugarDockerized#56]
Is it possible to run the Sugar Unit Tests on an instance running under these containers? I have been trying but struggling to get them to run. I tried just running from my host but the database connection failed on the {old} tests.

Any suggestions would be appreciated or if you do suggest running the tests in the containerized version please let me know. 

Thank you very much

**Comment by esimonetti** [comment]
Hey Shad, honestly I have not tried. Have you tried from the utilities bash script to run a cli? That will run a command on the cron container that has access to all the elements of the stack

**Comment by ShadMickelberry** [comment]
Thanks a lot Enrico. I'll try that. I tried via ssh directly into the sugar-web1 container. I may try a bit more on that. Could be due to composer not being installed there.

I'll let you know

**Comment by ShadMickelberry** [comment]
Hey @esimonetti, 

Here is what I've tried. 
$ ./utilities/runcli.sh "cd tests/{old} && ../../vendor/bin/phpunit"
bash: ../../vendor/bin/phpunit: Permission denied
$ ./utilities/runcli.sh "cd tests/{old} && chmod +x ../../vendor/bin/phpunit && ../../vendor/bin/phpunit"
You need to setup the project dependencies
$ ./utilities/runcli.sh "composer install"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/ldap v3.4.11 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - symfony/ldap v3.4.11 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for symfony/ldap v3.4.11 -> satisfiable by symfony/ldap[v3.4.11].

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gmp.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-imap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/docker.ini
    - /usr/local/etc/php/conf.d/opcache.ini
    - /usr/local/etc/php/conf.d/tideways.ini
    - /usr/local/etc/php/conf.d/xhprof.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

I already did composer install from the host and installed the dependencies but they don't seem to be taking. I also tried updating all permissions but it didn't seem to do the trick. 

I also looked into adding the ldap extension but that is a bit over my head in Docker right now.

Running from the host BTW I run into database connection errors. No big deal if this is a pain to implement or if you aren't going to have time to investigate.

**Comment by esimonetti** [comment]
I had a look at it and I could get the phpunit to work without too much fuss. I am encountering some problems in terms of the js side of things though so I won't do that at this stage.
Checkout the latest version and give it a go now.

After copying the test in the right location, the following commands should do the trick:
```
./utilities/runcli.sh composer install
./utilities/runcli.sh chmod +x vendor/bin/phpunit
./utilities/runcli.sh "cd tests/unit-php && ../../vendor/bin/phpunit"
./utilities/runcli.sh "cd tests/{old} && ../../vendor/bin/phpunit"
```

Cheers

**Comment by ShadMickelberry** [comment]
Awesome. Thanks a lot Enrico. I can run the composer install now. I appreciate your help.
