### ISSUE TITLE
Problem withe Redis and MacOS X

### ISSUE THREAD

**Issue by pnlem** [esimonetti/SugarDockerized#60]
Hello, 
I'm having a problem with Redis and Mac OS X. When I start my sugardockerized, sugar-redis is not starting. I have this error in the log of the container : 
M 13 Mar 11:10:22.765 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 13 Mar 11:10:22.765 # Server initialized
1:M 13 Mar 11:10:22.776 # Can't handle RDB format version 9
1:M 13 Mar 11:10:22.777 # Fatal error loading the DB: Invalid argument. Exiting.

The problem seems to be related to the way of docker for mac manage the image and containers. Is there a way to change my configuration of my mac ? 
Regards
Pierre-Nicolas

**Comment by esimonetti** [comment]
Hi Pierre-Nicolas,

I am not sure to be honest. For performance reasons of the file system, I do not run any longer the stack on OSX, but I run it in the provided VirtualBox image at the bottom of the README.md.


If you want to attempt solving the issue, have you tried googling the issue messages? 
Have those results helped in any way? Some top results that I glanced at are these two:
https://github.com/docker-library/redis/issues/35
https://github.com/bitnami/bitnami-docker-redis/issues/82

See if they help you

**Comment by pnlem** [comment]
Hi Enrico, 
Thank you for your answer. I finally found a solution, I've added in php71-local-build.yml this insctruction for redis : command: ["redis-server", "--appendonly", "yes"]. It's working now. One more thing about your configuration. Your are using one VirtualBox image per project ? Actually I have one SugarDockerized by project, if I use VirtualBox I'm afraid that It will be complicated to manage and saturate my SSD. 

Regards, 
Pierre-Nicolas

**Comment by esimonetti** [comment]
Hi Pierre-Nicolas,

Glad to hear!
No I use a single Virtualbox image (like if it was my desktop basically). It does not use much more space than having it local, as the debian host is pretty minimal and has no gui.

I use a single clone of SugarDockerized, leveraging the backup and restore tools, so that i can easily switch between different installations and different stacks for it.

Give it a try!

**Comment by pnlem** [comment]
Thanks for your answer, I will try ! 
Pierre-Nicolas
