### ISSUE TITLE
PDO MySQL removed in latest 7.9 stack

### ISSUE THREAD

**Issue by vjaro** [esimonetti/SugarDockerized#68]
Hi @esimonetti 

I've noticed that the latest sugar79 stack does not include pdo_mysql driver anymore.
Was this intended in preparation to migrate into sugar8?

How can i add back the pdo_mysql driver in the stack?
Thanks in anticipation.

**Comment by esimonetti** [comment]
Hi there,

As Sugar does not use and as far as I am aware never used pdo. At this stage I won't be adding it into the docker images provided here, as it is not needed by the product itself.

You do have few alternatives:
1- you could create your new container that connects to mysql on localhost, if the Sugar code base is not needed
2- you could locally build your own modified versions of the containers, by editing the containers configurations and building them locally by using the provided "-local-build.yml" docker-compose yml files (for 7.9 https://github.com/esimonetti/SugarDockerized/blob/master/stacks/sugar79/php71-local-build.yml)

Hope it helps

Hope it helps
