### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by jhoffmann** [esimonetti/SugarDockerized#69]
Hi Enrico,

I was hoping to use parts of this for another Sugar customer.  Would it be possible to include a license file, or at least something in the README?

**Comment by esimonetti** [comment]
Hey John!

Do you mean the project's license? It is there already: https://github.com/esimonetti/SugarDockerized/blob/master/LICENSE

Does that answer your question?

Cheers

**Comment by jhoffmann** [comment]
Yes sorry :(
