### ISSUE TITLE
Empty WWW Dir

### ISSUE THREAD

**Issue by olson101** [esimonetti/SugarDockerized#70]
I am not seeing anything in /var/www/sugar

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

  | Parent Directory |   | - |  

Running 
Sugar9  Stack

**Comment by olson101** [comment]
![image](https://user-images.githubusercontent.com/1063517/69170671-1c1eca80-0ac0-11ea-9dd5-23f4cdd8b428.png)

**Comment by ShadMickelberry** [comment]
Hello Jon,

Did you copy the files of a sugar instance (existing or new) into this path? It should also be located in /var/www/html/sugar on the sugar-web1 container.

**Comment by olson101** [comment]
I missed that step, This fixed it.

Thanks!

**Comment by ShadMickelberry** [comment]
No problem. Glad to help.

**Comment by esimonetti** [comment]
Thanks @ShadMickelberry for your help!
