### ISSUE TITLE
Xdebug on Mac

### ISSUE THREAD

**Issue by ShadMickelberry** [esimonetti/SugarDockerized#87]
Hello,

I have been playing around with running the php73-mac.yml stack locally after my virtual machine seeming to slow down over time. I have it up and running and at least performance seems about the same as on the VM.

I changed the Mysql forward port from 3306 to 3336 so I could connect to the database directly.

The only issue I seem to be having is I cannot get Xdebug to work. Uncommented the section in the Dockerfile and updated the Proxy Settings to 127.0.0.1 from 10.10.10.1 as I had while in the virtual machine. 

I know you don't use this setup Enrico but would you have any suggestions to try? 

Thank you very much

**Comment by ShadMickelberry** [comment]
If it helps at all it seems the xdebug.ini copy command may be the issue. I'm not sure of the reason but when I look in the sugar-web1 container there is no xdebug file in /usr/local/etc/php/conf.d/ even after uncommenting the Dockerfile and rebuilding.

Thanks againg

**Comment by ShadMickelberry** [comment]
I did some more investigating and it looks like the Docker Hub image (esimonetti/sugardockerized:php7.3-apache-1.28)  doesn't copy the xdebug file over in the Dockerfile which I understand the reasoning behind. Do you happen to have the Dockerfile for that repo that I can modify please?

**Comment by esimonetti** [comment]
You could always use the local deployment file. Now I merged a PR from a contributor that *should* allow to enable and disable xdebug runtime. Let me know how you go

**Comment by ShadMickelberry** [comment]
I agree just using the local deployment has been working. There is one issue on the current version however that I was able to work out but I'll deploy a separate issue for that.
