### ISSUE TITLE
Elasticsearch does not work on Docker windows 

### ISSUE THREAD

**Issue by jsomhorst** [esimonetti/SugarDockerized#88]
Hi, 

since the latest installation of Docker for windows elasticsearch doesn't boot anymore. It crashes with a error like: 

Sugar-elasticsearch | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144].

**Comment by ShadMickelberry** [comment]
Hello,

In my opinion this is more of an upstream Elasticsearch setting. Not really even an issue it is just likely using more memory now.
See a resolution here:
https://github.com/elastic/elasticsearch-docker/issues/92
