### ISSUE TITLE
Toothpaste does not install in the Sugar 12 environment

### ISSUE THREAD

**Issue by bickart** [esimonetti/SugarDockerized#99]
Hi -

It's not possible to install toothpaste using the install.sh command using Sugar 12. It throws errors. 

 Problem 1
    - symfony/console[v4.3.0, ..., v4.3.11] require php ^7.1.3 -> your php version (8.0.27) does not satisfy that requirement.
    - esimonetti/toothpaste dev-master requires symfony/console 4.3.* -> satisfiable by symfony/console[v4.3.0, ..., v4.3.11].
    - Root composer.json requires esimonetti/toothpaste dev-master -> satisfiable by esimonetti/toothpaste[dev-master].

**Comment by esimonetti** [comment]
See if the new version of toothpaste fixes the problem, with the contribution that was made there

**Comment by esimonetti** [comment]
Assumed fixed as I have not heard back
